### ISSUE TITLE
Update das_import needed?

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/SAMADhi#14]
DAS authentification with a grid certificate is now mandatory as [per hn announcement](https://hypernews.cern.ch/HyperNews/CMS/get/cernCompAnnounce/1144/1.html) 

@BrieucF observes a crash of [`GridIn/runPostCrab.py`](https://github.com/cp3-llbb/GridIn/blob/master/scripts/runPostCrab.py) which seems to orginate from the changes in authentification protocols (trace below)

Could someone (more at ease with certificate handling than myself, maybe @blinkseb ?) have a look at updating [`das_import.py`](https://github.com/cp3-llbb/SAMADhi/blob/master/scripts/das_import.py) ? It seems the recommended way is to use the CMSSW wrapper at `/cvmfs/cms.cern.ch/common/das_client`

Thanks!

```
runPostCrab.py crab_HToZATo2L2B_MH-3000_MA-2000_13TeV-madgraph_Fall15MiniAODv1.py
##### Get information out of the crab config file (work area, dataset, pset)
done

##### Check if the dataset exists in the database
calling das_import
Traceback (most recent call last):
  File "/nfs/scratch/fynu/bfrancois/framework/CMSSW_7_6_5/bin/slc6_amd64_gcc493/runPostCrab.py", line 369, in <module>
    main() 
  File "/nfs/scratch/fynu/bfrancois/framework/CMSSW_7_6_5/bin/slc6_amd64_gcc493/runPostCrab.py", line 246, in main
    das_import.main()
  File "/nfs/scratch/fynu/bfrancois/framework/CMSSW_7_6_5/bin/slc6_amd64_gcc493/das_import.py", line 237, in main
    jsondict1 = get_data(host, query1, idx, 1, debug, thr, ckey, cert, das_h)
  File "/nfs/scratch/fynu/bfrancois/framework/CMSSW_7_6_5/bin/slc6_amd64_gcc493/das_import.py", line 150, in get_data
    fdesc = opener.open(req)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden 
```

**Comment by BrieucF** [comment]
Everything needed to fix this is already available in das_import. Fix done in [GridIn](https://github.com/cp3-llbb/GridIn) repo via [this](https://github.com/cp3-llbb/GridIn/pull/83) PR.

**Comment by OlivierBondu** [comment]
thanks !
